fix path on windows
imgcook/pipcook-script pull request #16
Opened 2021-08-20 09:35 UTC by FeelyChau

2021-08-20 10:01 UTC, rickycao-qy requested changes

2021-08-20 10:01 UTC, rickycao-qy commented on scripts/object-detection-yolo/src/datasource.ts
> +  console.log('train:', statisticPascalVoc(train));
shall we remove these logs

2021-08-20 10:18 UTC, FeelyChau commented on scripts/object-detection-yolo/src/datasource.ts
> +  console.log('train:', statisticPascalVoc(train));
Fixed.

2021-08-23 05:52 UTC, rickycao-qy approved these changes
LGTM

2021-08-23 08:24 UTC, merged